# Generated by Django 3.2.8 on 2021-12-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='video',
            field=models.FileField(upload_to='media/'),
        ),
    ]
