# Generated by Django 3.2.8 on 2021-12-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0002_alter_courses_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
            ],
        ),
    ]
