# Generated by Django 3.2.8 on 2021-12-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0004_alter_userprofession_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofession',
            name='profession',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Teacher', max_length=50),
        ),
    ]
