# Generated by Django 3.2.8 on 2021-12-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0005_alter_userprofession_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofession',
            name='profession',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofession',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
