# Generated by Django 3.2.8 on 2021-12-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0007_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='username',
            new_name='access_name',
        ),
    ]
