# Generated by Django 3.2.8 on 2021-12-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0008_rename_username_cart_access_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Kotlin', 'Kotlin'), ('Other', 'Other')], default='Python', max_length=150),
        ),
    ]
